# Jekyll configuration for GitHub Pages

# Site settings
title: Technology Blog
email: your-email@example.com
description: >-
  A professional blog about technology with guides, reviews, news, tutorials, and case studies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dirakhil.github.io/Autonomous-AI-Agents" # the base hostname & protocol for your site
twitter_username: dirakhil
github_username: dirakhil

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  - series

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Content Agent"
      comments: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Google Analytics (add your ID when ready)
google_analytics: UA-XXXXXXXX-X

# Disqus Comments (add your shortname when ready)
disqus:
  shortname: your-disqus-shortname
